version: "3.8"
services:
  front:
    build:
      context: ./front
    ports:
      - 3000:3000
    volumes:
      - ./front:/usr/src/front
      - node_modules:/usr/src/front/node_modules
    command: sh -c "yarn dev"

volumes:
  node_modules:
