FROM node:14.17.0-alpine3.13

ENV LANG                              C.UTF-8
ENV TZ                                Asia/Tokyo

WORKDIR /usr/src/front

# COPY package.json ${WORKDIR}
# COPY yarn.lock ${WORKDIR}

# RUN yarn install

# COPY . ${WORKDIR}

EXPOSE 3000
